version: 0.0
os: linux
files:
  - source: /target/spring-petclinic-3.3.0-SNAPSHOT.jar
    destination: /opt/
    overwrite: true

hooks:
  StopStart:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
      
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
