version: 0.0
os: linux
files:
  - source: target/spring-petclinic-*.jar
    destination: /var/www/html/
 
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
 AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root

