version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      # - mvn install  # For Maven projects
  pre_build:
    commands:
      - echo Pre-build phase...
       - mvn clean  # Clean up before building
  build:
    commands:
      - echo Building the project...
      - mvn package # Package the application (jar/war files will be generated in the target directory)
      - java -jar target/*.jar
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'  # Include all files
  base-directory: 'target'  # This is where Maven typically places the build artifacts
  discard-paths: no  # Keep directory structure in the artifact

cache:
  paths:
    - '/root/.m2/**/*'  # Cache Maven dependencies to speed up builds
