version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto11 # Specify Java 17 runtime version
    commands:
      - echo Verifying Java version...
      - java -version # Ensure the correct Java version is being used
      - javac -version # Ensure the correct Java compiler version is being used
      - echo Installing Maven...
      - curl -o apache-maven-3.9.1-bin.zip https://archive.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.zip
      - unzip apache-maven-3.9.1-bin.zip
      - export M2_HOME=$PWD/apache-maven-3.9.1
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version # Validate Maven installation
 
  pre_build:
    commands:
      - echo Caching Maven dependencies...
      - mvn dependency:go-offline -B # Cache Maven dependencies
 
  build:
    commands:
      - echo Building the application...
      - mvn clean package -DskipTests -B # Compile and package the application in batch mode
 
  post_build:
    commands:
      - echo Build completed successfully!
 
 
artifacts:
  files:
    - '**/*'   
cache:
  paths:
    - "/root/.m2/**/*" # Cache Maven dependencies for faster builds
